"""Reusable experimental utilities for the Neural Chameleon circuit project."""

from .experimental_splits import (
    DEFAULT_SPLIT_DIR,
    LockedSafetySplitError,
    load_experimental_split,
)
from .component_analysis import (
    COMPONENT_KINDS,
    RANDOM_CONTROL_LAYERS,
    SELECTED_LAYERS,
    TruncatedComponentResult,
    TruncatedComponentRunner,
    summarize_component_types,
)

from .interventions import (
    ActivationCache,
    ActivationKind,
    CapturedActivation,
    ConditionBatch,
    LinearProbe,
    PairedBatch,
    PairedInterventionRunner,
    PatchSite,
    RunResult,
    induction_fraction,
    recovery_fraction,
)
from .individual_components import (
    CANDIDATES,
    CANDIDATE_BY_ID,
    ELIGIBLE_LAYERS,
    NUM_QUERY_HEADS,
    SCREEN_METHODS,
    ComponentCandidate,
    ComponentScreeningRunner,
    MultiCandidatePatchRunner,
    MultiPatchResult,
    ScreeningBatchResult,
    component_set_sha256,
    eligible_candidates,
    masked_example_mean,
    repeat_condition,
    summarize_discovery_candidates,
)
from .localization import (
    ExampleTokenAlignment,
    TokenRegion,
    TruncatedMonitorResult,
    TruncatedMonitorRunner,
    align_paired_prompts,
    aligned_patch_indices,
    identity_patch_indices,
    patch_aligned_residual,
    summarize_localization,
)

__all__ = [
    "ActivationCache",
    "ActivationKind",
    "COMPONENT_KINDS",
    "CANDIDATES",
    "CANDIDATE_BY_ID",
    "CapturedActivation",
    "ConditionBatch",
    "DEFAULT_SPLIT_DIR",
    "ExampleTokenAlignment",
    "ELIGIBLE_LAYERS",
    "LinearProbe",
    "LockedSafetySplitError",
    "MultiCandidatePatchRunner",
    "MultiPatchResult",
    "NUM_QUERY_HEADS",
    "PairedBatch",
    "PairedInterventionRunner",
    "PatchSite",
    "RANDOM_CONTROL_LAYERS",
    "SCREEN_METHODS",
    "ScreeningBatchResult",
    "RunResult",
    "SELECTED_LAYERS",
    "TokenRegion",
    "TruncatedMonitorResult",
    "TruncatedMonitorRunner",
    "TruncatedComponentResult",
    "TruncatedComponentRunner",
    "ComponentCandidate",
    "ComponentScreeningRunner",
    "align_paired_prompts",
    "aligned_patch_indices",
    "identity_patch_indices",
    "induction_fraction",
    "component_set_sha256",
    "eligible_candidates",
    "load_experimental_split",
    "masked_example_mean",
    "patch_aligned_residual",
    "recovery_fraction",
    "repeat_condition",
    "summarize_localization",
    "summarize_component_types",
    "summarize_discovery_candidates",
]
